export const projectsData = [
    // {
    //     image: '/projects/.png',
    //     title: "",
    //     framework: "",
    //     repo: "",
    //     site: "",
    //     category: "",
    // },
    {
        image: '/projects/GuessPaint-App.png',
        title: "GuessPaint App",
        framework: "Java",
        repo: "",
        site: "https://play.google.com/store/apps/details?id=com.casuals4fun.guesspaint",
        category: "app",
    },
    {
        image: '/projects/GuessPaint.png',
        title: "GuessPaint",
        framework: "Vite, Socket.IO",
        repo: "https://github.com/Casuals4Fun/GuessPaint",
        site: "https://guesspaint.vercel.app",
        category: "web",
    },
    {
        image: '/projects/ToDo-Tasks-App.png',
        title: "ToDo Tasks App",
        framework: "Java",
        repo: "",
        site: "https://play.google.com/store/apps/details?id=com.casuals4fun.todotasks",
        category: "app",
    },
    {
        image: '/projects/ToDo-Tasks.png',
        title: "ToDo Tasks",
        framework: "Vite",
        repo: "https://github.com/Casuals4Fun/ToDo-Tasks",
        site: "https://task-track-app.vercel.app",
        category: "web",
    },
    {
        image: '/projects/GitHub-Clone.png',
        title: "GitHub Clone",
        framework: "Vite",
        repo: "https://github.com/Shubham-Lal/GitHub-Clone",
        site: "https://github.shubhamlal.in",
        category: "web",
    },
    {
        image: '/projects/WePaint-App.png',
        title: "WePaint App",
        framework: "Java",
        repo: "",
        site: "https://play.google.com/store/apps/details?id=com.casuals4fun.wepaint",
        category: "app",
    },
    {
        image: '/projects/WePaint.png',
        title: "WePaint",
        framework: "Next.js, Socket.IO",
        repo: "https://github.com/Casuals4Fun/WePaint",
        site: "https://drawing.shubhamlal.in",
        category: "web",
    },
    {
        image: '/projects/CrowdFunding.png',
        title: "CrowdFunding",
        framework: "Solidity, TailwindCSS",
        repo: "https://github.com/Shubham-Lal/Crowdfunding-Blockchain",
        site: "",
        category: "web",
    },
    {
        image: '/projects/Krypt.png',
        title: "Krypt",
        framework: "Solidity, TailwindCSS",
        repo: "https://github.com/Shubham-Lal/Krypt-Blockchain-Transaction",
        site: "",
        category: "web",
    },
    {
        image: '/projects/ECommerce-Site-v2.png',
        title: "ECommerce Site v2",
        framework: "MERN Stack, TailwindCSS",
        repo: "https://github.com/Shubham-Lal/ECommerce-Site-v2",
        site: "https://certystore-v2.pages.dev",
        category: "web",
    },
    {
        image: '/projects/Reddit-Clone.png',
        title: "Reddit Clone",
        framework: "NextJS, CHAKRA UI, Firebase",
        repo: "https://github.com/Shubham-Lal/Reddit-Clone",
        site: "https://r-clone.vercel.app",
        category: "web",
    },
    {
        image: '/projects/Question-Answering-AI.png',
        title: "Questions Answering AI",
        framework: "Vite, OPENAI",
        repo: "https://github.com/Shubham-Lal/Question-Answering-AI",
        site: "",
        category: "web",
    },
    {
        image: '/projects/Image-Generator-AI.png',
        title: "Image Generator AI",
        framework: "Vite, OPENAI, Tailwindcss",
        repo: "https://github.com/Shubham-Lal/Image-Generator",
        site: "",
        category: "web",
    },
    {
        image: '/projects/UbuntuOS.png',
        title: "UbuntuOS",
        framework: "NextJS, Tailwindcss",
        repo: "https://github.com/Shubham-Lal/Portfolio-v2",
        site: "https://shubhamlal.in",
        category: "web",
    },
    {
        image: '/projects/Clang-Social-App.png',
        title: "Clang Social App",
        framework: "Java",
        repo: "",
        site: "https://play.google.com/store/apps/details?id=com.casuals4fun.clang_social",
        category: "app",
    },
    {
        image: '/projects/Clang-Social.png',
        title: "Clang Social",
        framework: "ReactJS, MongoDB",
        repo: "https://github.com/Casuals4Fun/ClangSocial",
        site: "https://clangsocial.netlify.app",
        category: "web",
    },
    {
        image: '/projects/Clang-Social-v1.png',
        title: "Clang Social v1",
        framework: "NextJS, Sanity",
        repo: "https://github.com/Shubham-Lal/ClangSocial-v1",
        site: "https://clang-social.netlify.app",
        category: "web",
    },
    {
        image: '/projects/Keeper.png',
        title: "Keeper",
        framework: "ReactJS, MongoDB",
        repo: "https://github.com/Shubham-Lal/Keeper",
        site: "https://keeper-demo.netlify.app",
        category: "web",
    },
    {
        image: '/projects/Infix-Operations.png',
        title: "Infix Operations",
        framework: "HTML, CSS, JS",
        repo: "https://shubham-lal.github.io/infix_operation",
        site: "https://github.com/Shubham-Lal/Infix-Operation",
        category: "web",
    },
    {
        image: '/projects/HammerOBots.png',
        title: "HammerOBots",
        framework: "Unreal Engine",
        repo: "",
        site: "https://play.google.com/store/apps/details?id=com.Casuals4Fun.HammerOBots",
        category: "game",
    },
    {
        image: '/projects/Space-Shooter.webp',
        title: "Space Shooter",
        framework: "PyGame",
        repo: "https://github.com/Shubham-Lal/SpaceShooter",
        site: "",
        category: "game",
    },
    {
        image: '/projects/Face-Mask-Detection.webp',
        title: "Face Mask Detection",
        framework: "Python",
        repo: "https://github.com/Shubham-Lal/Face-Mask-Detection",
        site: "",
        category: "software",
    },
    {
        image: '/projects/Items-Detector.webp',
        title: "Items Detector",
        framework: "Python",
        repo: "https://github.com/Shubham-Lal/Items-Detector",
        site: "",
        category: "software",
    },
    {
        image: '/projects/JARVIS.png',
        title: "J.A.R.V.I.S",
        framework: "Python",
        repo: "https://github.com/Shubham-Lal/JARVIS",
        site: "",
        category: "software",
    },
    {
        image: '/projects/TicTacToe.jpg',
        title: "Tic Tac Toe",
        framework: "Java",
        repo: "https://github.com/Shubham-Lal/TicTacToe",
        site: "",
        category: "game",
    },
    {
        image: '/projects/Facial-Recognition-Attendance.webp',
        title: "Facial Recognition Attendance",
        framework: "Python",
        repo: "https://github.com/Shubham-Lal/Facial-Recognition-Attendance",
        site: "",
        category: "software",
    },
];

export const projectsNav = [
    {
        name: "all",
    },
    {
        name: "web",
    },
    {
        name: "game",
    },
    {
        name: "software",
    },
    {
        name: "app",
    }
];