export const projectsData = [
    {
        image: '/projects/GitHub-Clone.png',
        title: "GitHub Clone",
        framework: "Vite",
        link: "https://github.shubhamlal.in",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/CrowdFunding.png',
        title: "CrowdFunding",
        framework: "Solidity & TailwindCSS",
        link: "https://github.com/Shubham-Lal/Crowdfunding-Blockchain",
        button: "Repo",
        category: "web",
    },
    {
        image: '/projects/Krypt.png',
        title: "Krypt",
        framework: "Solidity & TailwindCSS",
        link: "https://github.com/Shubham-Lal/Krypt-Blockchain-Transaction",
        button: "Repo",
        category: "web",
    },
    {
        image: '/projects/ECommerce-Site-v2.png',
        title: "ECommerce Site v2",
        framework: "MERN Stack & TailwindCSS",
        link: "https://github.com/Shubham-Lal/ECommerce-Site-v2",
        button: "Repo",
        category: "web",
    },
    {
        image: '/projects/Reddit-Clone.png',
        title: "Reddit Clone",
        framework: "NextJS, CHAKRA & Firebase",
        link: "https://r-clone.vercel.app",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/Question-Answering-AI.png',
        title: "Questions Answering AI",
        framework: "Vite & OPENAI",
        link: "https://github.com/Shubham-Lal/Question-Answering-AI",
        button: "Repo",
        category: "web",
    },
    {
        image: '/projects/Image-Generator-AI.png',
        title: "Image Generator AI",
        framework: "Vite, OPENAI & Tailwindcss",
        link: "https://github.com/Shubham-Lal/Image-Generator",
        button: "Repo",
        category: "web",
    },
    {
        image: '/projects/UbuntuOS.png',
        title: "UbuntuOS",
        framework: "NextJS & Tailwindcss",
        link: "https://ubuntuos.pages.dev",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/Clang-Social.png',
        title: "Clang Social",
        framework: "ReactJS & MongoDB",
        link: "https://clangsocial.netlify.app",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/Clang-Social-v1.png',
        title: "Clang Social v1",
        framework: "NextJS & Sanity",
        link: "https://clang-social.netlify.app",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/Keeper.png',
        title: "Keeper",
        framework: "ReactJS & MongoDB",
        link: "https://keeper-demo.netlify.app",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/Infix-Operations.png',
        title: "Infix Operations",
        framework: "HTML, CSS & JS",
        link: "https://shubham-lal.github.io/infix_operation",
        button: "Site",
        category: "web",
    },
    {
        image: '/projects/HammerOBots.png',
        title: "HammerOBots",
        framework: "Unreal Engine",
        link: "https://play.google.com/store/apps/details?id=com.Casuals4Fun.HammerOBots",
        button: "Play Store",
        category: "game",
    },
    {
        image: '/projects/Clang-Social-App.png',
        title: "Clang Social App",
        framework: "Java",
        link: "https://play.google.com/store/apps/details?id=com.casuals4fun.clang_social",
        button: "Play Store",
        category: "app",
    },
    {
        image: '/projects/Space-Shooter.webp',
        title: "Space Shooter",
        framework: "PyGame",
        link: "https://github.com/Shubham-Lal/SpaceShooter",
        button: "Github Repo",
        category: "game",
    },
    {
        image: '/projects/Face-Mask-Detection.webp',
        title: "Face Mask Detection",
        framework: "Python",
        link: "https://github.com/Shubham-Lal/Face-Mask-Detection",
        button: "Github Repo",
        category: "software",
    },
    {
        image: '/projects/Items-Detector.webp',
        title: "Items Detector",
        framework: "Python",
        link: "https://github.com/Shubham-Lal/Items-Detector",
        button: "Github Repo",
        category: "software",
    },
    {
        image: '/projects/JARVIS.png',
        title: "J.A.R.V.I.S",
        framework: "Python",
        link: "https://github.com/Shubham-Lal/JARVIS",
        button: "Github Repo",
        category: "software",
    },
    {
        image: '/projects/TicTacToe.jpg',
        title: "Tic Tac Toe",
        framework: "Java",
        link: "https://github.com/Shubham-Lal/TicTacToe",
        button: "Github Repo",
        category: "game",
    },
    {
        image: '/projects/Facial-Recognition-Attendance.webp',
        title: "Facial Recognition Attendance",
        framework: "Python",
        link: "https://github.com/Shubham-Lal/Facial-Recognition-Attendance",
        button: "Github Repo",
        category: "software",
    },
];

export const projectsNav = [
    {
        name: "all",
    },
    {
        name: "web",
    },
    {
        name: "game",
    },
    {
        name: "software",
    },
    {
        name: "app",
    }
];